// Mocks generated by Mockito 5.0.7 from annotations
// in calisthenics_logger_2/test/data/datasources/implementations/tracked_exercise_data_source_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:calisthenics_logger_2/data/datasources/database/tracked_exercise_db_helper.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [TrackedExerciseDbHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrackedExerciseDbHelper extends _i1.Mock
    implements _i2.TrackedExerciseDbHelper {
  MockTrackedExerciseDbHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<Map<String, dynamic>>> queryAllGivenNameAndDate(
          String? name, int? requestTimestamp) =>
      (super.noSuchMethod(
              Invocation.method(
                  #queryAllGivenNameAndDate, [name, requestTimestamp]),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i3.Future<List<Map<String, dynamic>>>);
}
